let citas = [
  { 'autor': 'Albert Einstein', 'texto': 'La imaginación es más importante que el conocimiento.' },
  { 'autor': 'Maya Angelou', 'texto': 'La gente olvidará lo que dijiste, la gente olvidará lo que hiciste, pero la gente nunca olvidará cómo la hiciste sentir.' },
  { 'autor': 'Mark Twain', 'texto': 'La mejor manera de predecir el futuro es crearlo.' },
  { 'autor': 'Oscar Wilde', 'texto': 'La única manera de librarse de una tentación es ceder ante ella.' },
  { 'autor': 'Eleanor Roosevelt', 'texto': 'Haz una cosa todos los días que te dé miedo.' },
  { 'autor': 'Winston Churchill', 'texto': 'El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el coraje para continuar.' },
  { 'autor': 'Ralph Waldo Emerson', 'texto': 'No temas entrar en la región desconocida, porque ahí es donde se encuentran las oportunidades.' },
  { 'autor': 'J.K. Rowling', 'texto': 'Es imposible vivir sin fracasar en algo, a menos que vivas con tanta precaución que podrías no haber vivido en absoluto, en cuyo caso has fallado por defecto.' },
  { 'autor': 'Vincent van Gogh', 'texto': 'No puedo cambiar la dirección del viento, pero puedo ajustar mis velas para siempre llegar a mi destino.' },
  { 'autor': 'Aristóteles', 'texto': 'Somos lo que hacemos repetidamente. La excelencia, entonces, no es un acto, sino un hábito.' },
  { 'autor': 'Coco Chanel', 'texto': 'La moda no sólo existe en los vestidos. La moda está en el cielo, en la calle, la moda tiene que ver con las ideas, la forma en que vivimos, lo que está sucediendo.' },
  { 'autor': 'Jim Rohn', 'texto': 'La única limitación a nuestra realización de mañana será nuestras dudas de hoy.' },
  { 'autor': 'Nelson Mandela', 'texto': 'La mayor gloria en vivir no está en nunca caer, sino en levantarnos cada vez que caemos.' },
  { 'autor': 'Malala Yousafzai', 'texto': 'No puedo creer que haya personas que tienen miedo de la educación. ¿Cómo pueden vivir sin saber?' },
  { 'autor': 'Stephen Hawking', 'texto': 'La inteligencia es la habilidad de adaptarse al cambio.' },
  { 'autor': 'William Shakespeare', 'texto': 'Nuestras dudas son traidores y nos hacen perder lo que a menudo podríamos ganar, por el miedo a intentarlo.' },
  { 'autor': 'Confucio', 'texto': 'Es mejor encender una vela que maldecir la oscuridad.' },
  { 'autor': 'Albert Camus', 'texto': 'En medio del invierno, aprendí por fin que había en mí un verano invencible.' },
  { 'autor': 'C. S. Lewis', 'texto': 'No puedes volver atrás y cambiar el principio, pero puedes empezar donde estás y cambiar el final.' },
  { 'autor': 'Jane Austen', 'texto': 'No hay encanto igual a la ternura del corazón.' },
  { 'autor': 'Pablo Picasso', 'texto': 'La inspiración existe, pero tiene que encontrarte trabajando.' },
  { 'autor': 'Helen Keller', 'texto': 'La vida es una aventura audaz, o no es nada en absoluto.' },
  { 'autor': 'Isaac Newton', 'texto': 'Lo que sabemos es una gota, lo que ignoramos es un océano.' },
  { 'autor': 'Marilyn Monroe', 'texto': 'La vida es demasiado importante como para ser tomada en serio.' },
  { 'autor': 'Sócrates', 'texto': 'La verdadera sabiduría está en reconocer la propia ignorancia.' },
  { 'autor': 'Freddie Mercury', 'texto': 'Yo no cambio por nadie, pero tú deberías haber cambiado esa cerradura.' },
  { 'autor': 'Coco Chanel', 'texto': 'La moda pasa, el estilo permanece.' },
  { 'autor': 'Isabel Allende', 'texto': 'La única manera de hacer un gran trabajo es amar lo que haces.' },
  { 'autor': 'Bruce Lee', 'texto': 'Absorbe lo útil, descarta lo inútil y agrega lo que es esencialmente tuyo.' },
  { 'autor': 'Cristiano Ronaldo', 'texto': 'No tengo tatuajes para no parecer un delincuente.' },
  { 'autor': 'Homer Simpson', 'texto': 'Es mejor estar callado y parecer tonto que hablar y despejar las dudas definitivamente.' },
  { 'autor': 'J.R.R. Tolkien', 'texto': 'Incluso la oscuridad debe pasar. Un nuevo día vendrá. Y cuando salga el sol, brillará más fuerte que nunca.' },
  { 'autor': 'Audrey Hepburn', 'texto': 'La belleza de una mujer no está en la ropa que usa, la figura que lleva o la forma en que peina su cabello.' },
  { 'autor': 'Frida Kahlo', 'texto': 'Pies, ¿para qué los quiero si tengo alas para volar?' },
  { 'autor': 'George Bernard Shaw', 'texto': 'La vida no consiste en encontrarse a uno mismo, sino en crearse a uno mismo.' },
  { 'autor': 'Bruce Springsteen', 'texto': 'La música es la revelación más poderosa y hermosa de lo que realmente somos.' },
  { 'autor': 'Jane Goodall', 'texto': 'Lo que haces marca la diferencia, y tienes que decidir qué tipo de diferencia quieres marcar.' },
  { 'autor': 'Oprah Winfrey', 'texto': 'Haz lo que tengas que hacer hasta que puedas hacer lo que quieras hacer.' },
  { 'autor': 'Walt Disney', 'texto': 'La mejor manera de predecir el futuro es crearlo.' },
  { 'autor': 'Arthur C. Clarke', 'texto': 'Cualquier tecnología suficientemente avanzada es indistinguible de la magia.' }
];
